import Head from 'next/head'
import Image from 'next/image'
import githublogo from '../res/iconmonstr-github-1.svg'
import styles from '../styles/Home.module.css'
import {motion} from "framer-motion"


export default function Home() {
  const variant = {
    hidden: { opacity: 0},
    enter: { opacity: 1},
    exit: { opacity: 0 },
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Esteban Rodriguez (ZEZEL,Z3ZEL) <motion.div
           variants={variant} // Pass the variant object into Framer Motion 
           initial="hidden" // Set the initial state to variants.hidden
           animate="enter" // Animated state to variants.enter
           exit="exit" // Exit state (used later) to variants.exit
           transition={{duration:1, type: 'ease out' }} // Set the transition to linear
           className=""
          
          
          > Portefolio</motion.div>
        </h1>

        <p className={styles.description}>

          <motion.div
            animate={{y:[0,10,0]}}
            transition = {{duration:8,type:"linear",repeat : Infinity}}
          >
          Developing on my free time.

          </motion.div>
        </p>


        <div className={styles.card}>
          Pleasure to make
        </div>
        <div className={styles.card}>
          Products
        </div>
        <div className={styles.card}>
          School project
        </div>



      </main>

      <footer className={styles.footer}>
        Email : estebanrodriguez17780@gmail.com
        <a href="https://github.com/Z3ZEL">
        <Image  src={githublogo} height={30} width={30} />
        </a>
      </footer>
    </div>
  )
}
